const locationOptions = [
  {
    label: '서울특별시',
    subOptions: [
      { label: '종로구' },
      { label: '중구' },
      { label: '용산구' },
      { label: '성동구' },
      { label: '광진구' },
      { label: '동대문구' },
      { label: '중랑구' },
      { label: '성북구' },
      { label: '강북구' },
      { label: '도봉구' },
      { label: '노원구' },
      { label: '은평구' },
      { label: '서대문구' },
      { label: '마포구' },
      { label: '양천구' },
      { label: '강서구' },
      { label: '구로구' },
      { label: '금천구' },
      { label: '영등포구' },
      { label: '동작구' },
      { label: '관악구' },
      { label: '서초구' },
      { label: '강남구' },
      { label: '송파구' },
      { label: '강동구' },
    ],
  },
  {
    label: '부산광역시',
    subOptions: [
      { label: '중구' },
      { label: '서구' },
      { label: '동구' },
      { label: '영도구' },
      { label: '부산진구' },
      { label: '동래구' },
      { label: '남구' },
      { label: '북구' },
      { label: '해운대구' },
      { label: '사하구' },
      { label: '금정구' },
      { label: '강서구' },
      { label: '연제구' },
      { label: '수영구' },
      { label: '사상구' },
      { label: '기장군' },
    ],
  },
  {
    label: '대구광역시',
    subOptions: [
      { label: '중구' },
      { label: '동구' },
      { label: '서구' },
      { label: '남구' },
      { label: '북구' },
      { label: '수성구' },
      { label: '달서구' },
      { label: '달성군' },
      { label: '군위군' },
    ],
  },
  {
    label: '인천광역시',
    subOptions: [
      { label: '중구' },
      { label: '동구' },
      { label: '미추홀구' },
      { label: '연수구' },
      { label: '남동구' },
      { label: '부평구' },
      { label: '계양구' },
      { label: '서구' },
      { label: '강화군' },
      { label: '옹진군' },
    ],
  },
  {
    label: '광주광역시',
    subOptions: [{ label: '동구' }, { label: '서구' }, { label: '남구' }, { label: '북구' }, { label: '광산구' }],
  },
  {
    label: '대전광역시',
    subOptions: [{ label: '동구' }, { label: '서구' }, { label: '중구' }, { label: '유성구' }, { label: '대덕구' }],
  },
  {
    label: '울산광역시',
    subOptions: [{ label: '동구' }, { label: '남구' }, { label: '북구' }, { label: '중구' }, { label: '울주군' }],
  },
  {
    label: '세종특별자치시',
    subOptions: [{ label: '세종시 전체' }],
  },
  {
    label: '경기도',
    subOptions: [
      { label: '수원시' },
      { label: '성남시' },
      { label: '의정부시' },
      { label: '안양시' },
      { label: '부천시' },
      { label: '광명시' },
      { label: '평택시' },
      { label: '동두천시' },
      { label: '안산시' },
      { label: '고양시' },
      { label: '과천시' },
      { label: '의왕시' },
      { label: '군포시' },
      { label: '하남시' },
      { label: '김포시' },
      { label: '광주시' },
      { label: '양주시' },
      { label: '구리시' },
      { label: '남양주시' },
      { label: '오산시' },
      { label: '시흥시' },
      { label: '파주시' },
      { label: '이천시' },
      { label: '안성시' },
      { label: '포천시' },
      { label: '여주시' },
      { label: '양평군' },
      { label: '가평군' },
      { label: '연천군' },
    ],
  },
  {
    label: '강원도',
    subOptions: [
      { label: '춘천시' },
      { label: '원주시' },
      { label: '강릉시' },
      { label: '동해시' },
      { label: '태백시' },
      { label: '속초시' },
      { label: '삼척시' },
      { label: '홍천군' },
      { label: '횡성군' },
      { label: '영월군' },
      { label: '평창군' },
      { label: '정선군' },
      { label: '철원군' },
      { label: '화천군' },
      { label: '양구군' },
      { label: '인제군' },
      { label: '고성군' },
      { label: '양양군' },
    ],
  },
  {
    label: '충청북도',
    subOptions: [
      { label: '청주시' },
      { label: '충주시' },
      { label: '제천시' },
      { label: '보은군' },
      { label: '옥천군' },
      { label: '영동군' },
      { label: '증평군' },
      { label: '진천군' },
      { label: '괴산군' },
      { label: '음성군' },
      { label: '단양군' },
    ],
  },
  {
    label: '충청남도',
    subOptions: [
      { label: '천안시' },
      { label: '공주시' },
      { label: '보령시' },
      { label: '아산시' },
      { label: '서산시' },
      { label: '논산시' },
      { label: '계룡시' },
      { label: '당진시' },
      { label: '금산군' },
      { label: '부여군' },
      { label: '서천군' },
      { label: '청양군' },
      { label: '홍성군' },
      { label: '예산군' },
      { label: '태안군' },
    ],
  },
  {
    label: '전라북도',
    subOptions: [
      { label: '전주시' },
      { label: '군산시' },
      { label: '익산시' },
      { label: '정읍시' },
      { label: '남원시' },
      { label: '김제시' },
      { label: '완주군' },
      { label: '진안군' },
      { label: '무주군' },
      { label: '장수군' },
      { label: '임실군' },
      { label: '순창군' },
      { label: '고창군' },
      { label: '부안군' },
    ],
  },
  {
    label: '전라남도',
    subOptions: [
      { label: '목포시' },
      { label: '여수시' },
      { label: '순천시' },
      { label: '나주시' },
      { label: '광양시' },
      { label: '담양군' },
      { label: '곡성군' },
      { label: '구례군' },
      { label: '고흥군' },
      { label: '보성군' },
      { label: '화순군' },
      { label: '장흥군' },
      { label: '강진군' },
      { label: '해남군' },
      { label: '영암군' },
      { label: '무안군' },
      { label: '함평군' },
      { label: '영광군' },
      { label: '장성군' },
      { label: '완도군' },
      { label: '진도군' },
      { label: '신안군' },
    ],
  },
  {
    label: '경상북도',
    subOptions: [
      { label: '포항시' },
      { label: '경주시' },
      { label: '김천시' },
      { label: '안동시' },
      { label: '구미시' },
      { label: '영주시' },
      { label: '영천시' },
      { label: '상주시' },
      { label: '문경시' },
      { label: '경산시' },
      { label: '의성군' },
      { label: '청송군' },
      { label: '영양군' },
      { label: '영덕군' },
      { label: '청도군' },
      { label: '고령군' },
      { label: '성주군' },
      { label: '칠곡군' },
      { label: '예천군' },
      { label: '봉화군' },
      { label: '울진군' },
      { label: '울릉군' },
    ],
  },
  {
    label: '경상남도',
    subOptions: [
      { label: '창원시' },
      { label: '김해시' },
      { label: '진주시' },
      { label: '양산시' },
      { label: '거제시' },
      { label: '통영시' },
      { label: '사천시' },
      { label: '밀양시' },
      { label: '함안군' },
      { label: '거창군' },
      { label: '합천군' },
      { label: '창녕군' },
      { label: '고성군' },
      { label: '남해군' },
      { label: '하동군' },
      { label: '함양군' },
      { label: '산청군' },
      { label: '의령군' },
    ],
  },
  {
    label: '제주특별자치도',
    subOptions: [{ label: '제주시' }, { label: '서귀포시' }],
  },
];

export default locationOptions;
