name: CI/CD for feat, develop and master branches

on:
  push:
    branches:
      - 'feat/**'
      - 'refactor/**'
      - develop
      - master

jobs:
  lint-and-test:
    if: startsWith(github.ref, 'refs/heads/feat/') || startsWith(github.ref, 'refs/heads/refactor/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run format -- --check

      - name: Run Tests
        run: npm test

  build-and-deploy:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build
        env:
          VITE_KAKAO_JS_KEY: ${{ secrets.VITE_KAKAO_JS_KEY }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Deploy to S3
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "Deploying to QA environment..."
            aws s3 sync dist/ s3://inplace.my --delete
          elif [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "Deploying to Production environment..."
            aws s3 sync dist/ s3://inplace.my --delete
          fi